# Generated by Django 2.2.2 on 2019-12-14 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 14, 22, 35, 48, 225624)),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2019, 12, 14, 22, 35, 48, 225624)),
        ),
    ]
