# Generated by Django 2.2.2 on 2019-12-14 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20191214_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode_type',
            name='id_choice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 14, 22, 43, 17, 20208)),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2019, 12, 14, 22, 43, 17, 20208)),
        ),
    ]
